package com.myBubble;

import com.myBubble.utils.CodeManager;

import org.junit.Test;

import static org.junit.Assert.*;

public class CodeManagerTest {

    /*=============================================================================
|          Task: Generate unique ID for app
|   Description: Tests check if CodeManager generates a code
*===========================================================================*/
    @Test
    //Checking that the codeManager generates a code
    public void code_isGenerated(){
        CodeManager cm = new CodeManager();
        String codeString = String.valueOf(cm.generateCode());

        assertNotNull(codeString);
    }

    @Test
    //Checking that the generated code is exactly 20 characters
    public void code_isLength(){
        CodeManager cm = new CodeManager();
        String codeString = String.valueOf(cm.generateCode());

        assertEquals(20, codeString.length());

    }

    @Test
    //Checking that the a different code is generated each time the codeManager is called
    public void code_isDifferent(){
        CodeManager cm = new CodeManager();
        String code1 = String.valueOf(cm.generateCode());
        String code2 = String.valueOf(cm.generateCode());

        assertNotEquals(code1, code2);
    }

    @Test
    //Checking that the structure of the code generated by the code manager is correct
    public void code_structureCorrect(){
        CodeManager cm = new CodeManager();
        String code1 = String.valueOf(cm.generateCode());

        assertEquals("4", code1);
    }



}
